package com.pein.repository.persistence;

import com.pein.repository.entity.ChannelWechat;

public interface ChannelWechatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_channel_wechat
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_channel_wechat
     *
     * @mbggenerated
     */
    int insert(ChannelWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_channel_wechat
     *
     * @mbggenerated
     */
    int insertSelective(ChannelWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_channel_wechat
     *
     * @mbggenerated
     */
    ChannelWechat selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_channel_wechat
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChannelWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_channel_wechat
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChannelWechat record);
}