package com.pein.repository.persistence;

import com.pein.repository.entity.ChannelUnion;

public interface ChannelUnionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_channel_union
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_channel_union
     *
     * @mbggenerated
     */
    int insert(ChannelUnion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_channel_union
     *
     * @mbggenerated
     */
    int insertSelective(ChannelUnion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_channel_union
     *
     * @mbggenerated
     */
    ChannelUnion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_channel_union
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChannelUnion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_channel_union
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChannelUnion record);
}