package com.pein.repository.persistence;

import com.pein.repository.entity.ChannelAli;

public interface ChannelAliMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_channel_ali
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_channel_ali
     *
     * @mbggenerated
     */
    int insert(ChannelAli record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_channel_ali
     *
     * @mbggenerated
     */
    int insertSelective(ChannelAli record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_channel_ali
     *
     * @mbggenerated
     */
    ChannelAli selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_channel_ali
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChannelAli record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_channel_ali
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChannelAli record);
}