package com.pein.repository.persistence;


import com.pein.repository.entity.OperateFlow;

public interface OperateFlowMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_operate_flow
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_operate_flow
     *
     * @mbggenerated
     */
    int insert(OperateFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_operate_flow
     *
     * @mbggenerated
     */
    int insertSelective(OperateFlow record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_operate_flow
     *
     * @mbggenerated
     */
    OperateFlow selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_operate_flow
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OperateFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_operate_flow
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OperateFlow record);
}