package com.pein.repository.persistence;


import com.pein.repository.entity.TraderFlow;

import java.util.List;

public interface TraderFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_trade_flow
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_trade_flow
     *
     * @mbggenerated
     */
    int insert(TraderFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_trade_flow
     *
     * @mbggenerated
     */
    int insertSelective(TraderFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_trade_flow
     *
     * @mbggenerated
     */
    TraderFlow selectByPrimaryKey(String id);

    /**
     * 根据appkey、instOutNo、channelCode查询订单
     * @param traderFlow
     * @return
     */
    TraderFlow selectByUniqueKey(TraderFlow traderFlow);

    /**
     * 根据appkey、instOutNo查询订单
     * @param traderFlow
     * @return
     */
    List<TraderFlow> selectByAppKeyAndOutNo(TraderFlow traderFlow);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_trade_flow
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TraderFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_trade_flow
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TraderFlow record);

    int updateByAppKeyAndOutNo(TraderFlow record);

    int updateByAppKeyAndOutNoAndCode(TraderFlow record);
}