package com.pein.repository.entity;

import java.util.Date;

public class ChannelAli {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_channel_ali.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_channel_ali.P_ID
     *
     * @mbggenerated
     */
    private String pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_channel_ali.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_channel_ali.CODE
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_channel_ali.MD5
     *
     * @mbggenerated
     */
    private String md5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_channel_ali.RSA_PUB
     *
     * @mbggenerated
     */
    private String rsaPub;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_channel_ali.RSA_PRI
     *
     * @mbggenerated
     */
    private String rsaPri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_channel_ali.MERCHANT_ID
     *
     * @mbggenerated
     */
    private Integer merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_channel_ali.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_channel_ali.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_channel_ali.ID
     *
     * @return the value of center_channel_ali.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_channel_ali.ID
     *
     * @param id the value for center_channel_ali.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_channel_ali.P_ID
     *
     * @return the value of center_channel_ali.P_ID
     *
     * @mbggenerated
     */
    public String getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_channel_ali.P_ID
     *
     * @param pId the value for center_channel_ali.P_ID
     *
     * @mbggenerated
     */
    public void setpId(String pId) {
        this.pId = pId == null ? null : pId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_channel_ali.NAME
     *
     * @return the value of center_channel_ali.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_channel_ali.NAME
     *
     * @param name the value for center_channel_ali.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_channel_ali.CODE
     *
     * @return the value of center_channel_ali.CODE
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_channel_ali.CODE
     *
     * @param code the value for center_channel_ali.CODE
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_channel_ali.MD5
     *
     * @return the value of center_channel_ali.MD5
     *
     * @mbggenerated
     */
    public String getMd5() {
        return md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_channel_ali.MD5
     *
     * @param md5 the value for center_channel_ali.MD5
     *
     * @mbggenerated
     */
    public void setMd5(String md5) {
        this.md5 = md5 == null ? null : md5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_channel_ali.RSA_PUB
     *
     * @return the value of center_channel_ali.RSA_PUB
     *
     * @mbggenerated
     */
    public String getRsaPub() {
        return rsaPub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_channel_ali.RSA_PUB
     *
     * @param rsaPub the value for center_channel_ali.RSA_PUB
     *
     * @mbggenerated
     */
    public void setRsaPub(String rsaPub) {
        this.rsaPub = rsaPub == null ? null : rsaPub.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_channel_ali.RSA_PRI
     *
     * @return the value of center_channel_ali.RSA_PRI
     *
     * @mbggenerated
     */
    public String getRsaPri() {
        return rsaPri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_channel_ali.RSA_PRI
     *
     * @param rsaPri the value for center_channel_ali.RSA_PRI
     *
     * @mbggenerated
     */
    public void setRsaPri(String rsaPri) {
        this.rsaPri = rsaPri == null ? null : rsaPri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_channel_ali.MERCHANT_ID
     *
     * @return the value of center_channel_ali.MERCHANT_ID
     *
     * @mbggenerated
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_channel_ali.MERCHANT_ID
     *
     * @param merchantId the value for center_channel_ali.MERCHANT_ID
     *
     * @mbggenerated
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_channel_ali.CREATE_TIME
     *
     * @return the value of center_channel_ali.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_channel_ali.CREATE_TIME
     *
     * @param createTime the value for center_channel_ali.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_channel_ali.STATUS
     *
     * @return the value of center_channel_ali.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_channel_ali.STATUS
     *
     * @param status the value for center_channel_ali.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}