package com.pein.repository.entity;

import java.util.Date;

public class ChannelWechat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_channel_wechat.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_channel_wechat.MCH_ID
     *
     * @mbggenerated
     */
    private String mchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_channel_wechat.APP_ID
     *
     * @mbggenerated
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_channel_wechat.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_channel_wechat.CODE
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_channel_wechat.API_KEY
     *
     * @mbggenerated
     */
    private String apiKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_channel_wechat.API_SECRET_PASSWORD
     *
     * @mbggenerated
     */
    private String apiSecretPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_channel_wechat.API_SECRET_URL
     *
     * @mbggenerated
     */
    private String apiSecretUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_channel_wechat.MERCHANT_ID
     *
     * @mbggenerated
     */
    private Integer merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_channel_wechat.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_channel_wechat.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_channel_wechat.ID
     *
     * @return the value of center_channel_wechat.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_channel_wechat.ID
     *
     * @param id the value for center_channel_wechat.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_channel_wechat.MCH_ID
     *
     * @return the value of center_channel_wechat.MCH_ID
     *
     * @mbggenerated
     */
    public String getMchId() {
        return mchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_channel_wechat.MCH_ID
     *
     * @param mchId the value for center_channel_wechat.MCH_ID
     *
     * @mbggenerated
     */
    public void setMchId(String mchId) {
        this.mchId = mchId == null ? null : mchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_channel_wechat.APP_ID
     *
     * @return the value of center_channel_wechat.APP_ID
     *
     * @mbggenerated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_channel_wechat.APP_ID
     *
     * @param appId the value for center_channel_wechat.APP_ID
     *
     * @mbggenerated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_channel_wechat.NAME
     *
     * @return the value of center_channel_wechat.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_channel_wechat.NAME
     *
     * @param name the value for center_channel_wechat.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_channel_wechat.CODE
     *
     * @return the value of center_channel_wechat.CODE
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_channel_wechat.CODE
     *
     * @param code the value for center_channel_wechat.CODE
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_channel_wechat.API_KEY
     *
     * @return the value of center_channel_wechat.API_KEY
     *
     * @mbggenerated
     */
    public String getApiKey() {
        return apiKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_channel_wechat.API_KEY
     *
     * @param apiKey the value for center_channel_wechat.API_KEY
     *
     * @mbggenerated
     */
    public void setApiKey(String apiKey) {
        this.apiKey = apiKey == null ? null : apiKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_channel_wechat.API_SECRET_PASSWORD
     *
     * @return the value of center_channel_wechat.API_SECRET_PASSWORD
     *
     * @mbggenerated
     */
    public String getApiSecretPassword() {
        return apiSecretPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_channel_wechat.API_SECRET_PASSWORD
     *
     * @param apiSecretPassword the value for center_channel_wechat.API_SECRET_PASSWORD
     *
     * @mbggenerated
     */
    public void setApiSecretPassword(String apiSecretPassword) {
        this.apiSecretPassword = apiSecretPassword == null ? null : apiSecretPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_channel_wechat.API_SECRET_URL
     *
     * @return the value of center_channel_wechat.API_SECRET_URL
     *
     * @mbggenerated
     */
    public String getApiSecretUrl() {
        return apiSecretUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_channel_wechat.API_SECRET_URL
     *
     * @param apiSecretUrl the value for center_channel_wechat.API_SECRET_URL
     *
     * @mbggenerated
     */
    public void setApiSecretUrl(String apiSecretUrl) {
        this.apiSecretUrl = apiSecretUrl == null ? null : apiSecretUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_channel_wechat.MERCHANT_ID
     *
     * @return the value of center_channel_wechat.MERCHANT_ID
     *
     * @mbggenerated
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_channel_wechat.MERCHANT_ID
     *
     * @param merchantId the value for center_channel_wechat.MERCHANT_ID
     *
     * @mbggenerated
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_channel_wechat.CREATE_TIME
     *
     * @return the value of center_channel_wechat.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_channel_wechat.CREATE_TIME
     *
     * @param createTime the value for center_channel_wechat.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_channel_wechat.STATUS
     *
     * @return the value of center_channel_wechat.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_channel_wechat.STATUS
     *
     * @param status the value for center_channel_wechat.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}