package com.pein.repository.entity;

import java.util.Date;

public class OperateFlow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_operate_flow.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_operate_flow.OPERATE_STATUS
     *
     * @mbggenerated
     */
    private String operateStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_operate_flow.OPERATE_STYLE
     *
     * @mbggenerated
     */
    private String operateStyle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_operate_flow.TRADE_ID
     *
     * @mbggenerated
     */
    private String tradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_operate_flow.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_operate_flow.ID
     *
     * @return the value of center_operate_flow.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_operate_flow.ID
     *
     * @param id the value for center_operate_flow.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_operate_flow.OPERATE_STATUS
     *
     * @return the value of center_operate_flow.OPERATE_STATUS
     *
     * @mbggenerated
     */
    public String getOperateStatus() {
        return operateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_operate_flow.OPERATE_STATUS
     *
     * @param operateStatus the value for center_operate_flow.OPERATE_STATUS
     *
     * @mbggenerated
     */
    public void setOperateStatus(String operateStatus) {
        this.operateStatus = operateStatus == null ? null : operateStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_operate_flow.OPERATE_STYLE
     *
     * @return the value of center_operate_flow.OPERATE_STYLE
     *
     * @mbggenerated
     */
    public String getOperateStyle() {
        return operateStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_operate_flow.OPERATE_STYLE
     *
     * @param operateStyle the value for center_operate_flow.OPERATE_STYLE
     *
     * @mbggenerated
     */
    public void setOperateStyle(String operateStyle) {
        this.operateStyle = operateStyle == null ? null : operateStyle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_operate_flow.TRADE_ID
     *
     * @return the value of center_operate_flow.TRADE_ID
     *
     * @mbggenerated
     */
    public String getTradeId() {
        return tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_operate_flow.TRADE_ID
     *
     * @param tradeId the value for center_operate_flow.TRADE_ID
     *
     * @mbggenerated
     */
    public void setTradeId(String tradeId) {
        this.tradeId = tradeId == null ? null : tradeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_operate_flow.CREATE_TIME
     *
     * @return the value of center_operate_flow.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_operate_flow.CREATE_TIME
     *
     * @param createTime the value for center_operate_flow.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}