package com.pein.repository.entity;

import java.util.Date;

public class TraderFlow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_trade_flow.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_trade_flow.PRO_SUBJECT
     *
     * @mbggenerated
     */
    private String proSubject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_trade_flow.PRO_DESC
     *
     * @mbggenerated
     */
    private String proDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_trade_flow.NOTIFY_URL
     *
     * @mbggenerated
     */
    private String notifyUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_trade_flow.TRADE_TYPE
     *
     * @mbggenerated
     */
    private String tradeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_trade_flow.TRADE_NO
     *
     * @mbggenerated
     */
    private String tradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_trade_flow.TRADE_STATES
     *
     * @mbggenerated
     */
    private String tradeStates;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_trade_flow.OUT_REFUND_NO
     *
     * @mbggenerated
     */
    private String outRefundNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_trade_flow.APP_KEY
     *
     * @mbggenerated
     */
    private String appKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_trade_flow.INST_TRADE_NO
     *
     * @mbggenerated
     */
    private String instTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_trade_flow.APP_ID
     *
     * @mbggenerated
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_trade_flow.MCH_ID
     *
     * @mbggenerated
     */
    private String mchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_trade_flow.AMOUNT
     *
     * @mbggenerated
     */
    private String amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_trade_flow.CHANNEL_CODE
     *
     * @mbggenerated
     */
    private String channelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_trade_flow.CHANNEL_URL
     *
     * @mbggenerated
     */
    private String channelUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_trade_flow.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_trade_flow.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_trade_flow.ID
     *
     * @return the value of center_trade_flow.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_trade_flow.ID
     *
     * @param id the value for center_trade_flow.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_trade_flow.PRO_SUBJECT
     *
     * @return the value of center_trade_flow.PRO_SUBJECT
     *
     * @mbggenerated
     */
    public String getProSubject() {
        return proSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_trade_flow.PRO_SUBJECT
     *
     * @param proSubject the value for center_trade_flow.PRO_SUBJECT
     *
     * @mbggenerated
     */
    public void setProSubject(String proSubject) {
        this.proSubject = proSubject == null ? null : proSubject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_trade_flow.PRO_DESC
     *
     * @return the value of center_trade_flow.PRO_DESC
     *
     * @mbggenerated
     */
    public String getProDesc() {
        return proDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_trade_flow.PRO_DESC
     *
     * @param proDesc the value for center_trade_flow.PRO_DESC
     *
     * @mbggenerated
     */
    public void setProDesc(String proDesc) {
        this.proDesc = proDesc == null ? null : proDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_trade_flow.NOTIFY_URL
     *
     * @return the value of center_trade_flow.NOTIFY_URL
     *
     * @mbggenerated
     */
    public String getNotifyUrl() {
        return notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_trade_flow.NOTIFY_URL
     *
     * @param notifyUrl the value for center_trade_flow.NOTIFY_URL
     *
     * @mbggenerated
     */
    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl == null ? null : notifyUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_trade_flow.TRADE_TYPE
     *
     * @return the value of center_trade_flow.TRADE_TYPE
     *
     * @mbggenerated
     */
    public String getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_trade_flow.TRADE_TYPE
     *
     * @param tradeType the value for center_trade_flow.TRADE_TYPE
     *
     * @mbggenerated
     */
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType == null ? null : tradeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_trade_flow.TRADE_NO
     *
     * @return the value of center_trade_flow.TRADE_NO
     *
     * @mbggenerated
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_trade_flow.TRADE_NO
     *
     * @param tradeNo the value for center_trade_flow.TRADE_NO
     *
     * @mbggenerated
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo == null ? null : tradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_trade_flow.TRADE_STATES
     *
     * @return the value of center_trade_flow.TRADE_STATES
     *
     * @mbggenerated
     */
    public String getTradeStates() {
        return tradeStates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_trade_flow.TRADE_STATES
     *
     * @param tradeStates the value for center_trade_flow.TRADE_STATES
     *
     * @mbggenerated
     */
    public void setTradeStates(String tradeStates) {
        this.tradeStates = tradeStates == null ? null : tradeStates.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_trade_flow.OUT_REFUND_NO
     *
     * @return the value of center_trade_flow.OUT_REFUND_NO
     *
     * @mbggenerated
     */
    public String getOutRefundNo() {
        return outRefundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_trade_flow.OUT_REFUND_NO
     *
     * @param outRefundNo the value for center_trade_flow.OUT_REFUND_NO
     *
     * @mbggenerated
     */
    public void setOutRefundNo(String outRefundNo) {
        this.outRefundNo = outRefundNo == null ? null : outRefundNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_trade_flow.APP_KEY
     *
     * @return the value of center_trade_flow.APP_KEY
     *
     * @mbggenerated
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_trade_flow.APP_KEY
     *
     * @param appKey the value for center_trade_flow.APP_KEY
     *
     * @mbggenerated
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey == null ? null : appKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_trade_flow.INST_TRADE_NO
     *
     * @return the value of center_trade_flow.INST_TRADE_NO
     *
     * @mbggenerated
     */
    public String getInstTradeNo() {
        return instTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_trade_flow.INST_TRADE_NO
     *
     * @param instTradeNo the value for center_trade_flow.INST_TRADE_NO
     *
     * @mbggenerated
     */
    public void setInstTradeNo(String instTradeNo) {
        this.instTradeNo = instTradeNo == null ? null : instTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_trade_flow.APP_ID
     *
     * @return the value of center_trade_flow.APP_ID
     *
     * @mbggenerated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_trade_flow.APP_ID
     *
     * @param appId the value for center_trade_flow.APP_ID
     *
     * @mbggenerated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_trade_flow.MCH_ID
     *
     * @return the value of center_trade_flow.MCH_ID
     *
     * @mbggenerated
     */
    public String getMchId() {
        return mchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_trade_flow.MCH_ID
     *
     * @param mchId the value for center_trade_flow.MCH_ID
     *
     * @mbggenerated
     */
    public void setMchId(String mchId) {
        this.mchId = mchId == null ? null : mchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_trade_flow.AMOUNT
     *
     * @return the value of center_trade_flow.AMOUNT
     *
     * @mbggenerated
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_trade_flow.AMOUNT
     *
     * @param amount the value for center_trade_flow.AMOUNT
     *
     * @mbggenerated
     */
    public void setAmount(String amount) {
        this.amount = amount == null ? null : amount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_trade_flow.CHANNEL_CODE
     *
     * @return the value of center_trade_flow.CHANNEL_CODE
     *
     * @mbggenerated
     */
    public String getChannelCode() {
        return channelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_trade_flow.CHANNEL_CODE
     *
     * @param channelCode the value for center_trade_flow.CHANNEL_CODE
     *
     * @mbggenerated
     */
    public void setChannelCode(String channelCode) {
        this.channelCode = channelCode == null ? null : channelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_trade_flow.CHANNEL_URL
     *
     * @return the value of center_trade_flow.CHANNEL_URL
     *
     * @mbggenerated
     */
    public String getChannelUrl() {
        return channelUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_trade_flow.CHANNEL_URL
     *
     * @param channelUrl the value for center_trade_flow.CHANNEL_URL
     *
     * @mbggenerated
     */
    public void setChannelUrl(String channelUrl) {
        this.channelUrl = channelUrl == null ? null : channelUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_trade_flow.CREATE_TIME
     *
     * @return the value of center_trade_flow.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_trade_flow.CREATE_TIME
     *
     * @param createTime the value for center_trade_flow.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_trade_flow.UPDATE_TIME
     *
     * @return the value of center_trade_flow.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_trade_flow.UPDATE_TIME
     *
     * @param updateTime the value for center_trade_flow.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        return "TraderFlow{" +
                "id='" + id + '\'' +
                ", proSubject='" + proSubject + '\'' +
                ", proDesc='" + proDesc + '\'' +
                ", notifyUrl='" + notifyUrl + '\'' +
                ", tradeType='" + tradeType + '\'' +
                ", tradeNo='" + tradeNo + '\'' +
                ", tradeStates='" + tradeStates + '\'' +
                ", outRefundNo='" + outRefundNo + '\'' +
                ", appKey='" + appKey + '\'' +
                ", instTradeNo='" + instTradeNo + '\'' +
                ", appId='" + appId + '\'' +
                ", mchId='" + mchId + '\'' +
                ", amount='" + amount + '\'' +
                ", channelCode='" + channelCode + '\'' +
                ", channelUrl='" + channelUrl + '\'' +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                '}';
    }
}